//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using Newtonsoft.Json;

namespace PayPal.Api
{
    /// <summary>
    /// Summary of invoice total and paid and refunded amounts grouped by currency code.
    /// <para>
    /// See <a href="https://developer.paypal.com/docs/api/">PayPal Developer documentation</a> for more information.
    /// </para>
    /// </summary>
    public class AmountSummary : PayPalSerializableObject
    {
        /// <summary>
        /// The total amount of the invoice.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "total_amount")]
        public Currency total_amount { get; set; }

        /// <summary>
        /// Payment summary of invoice data including the amount paid through PayPal and other sources
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "paid_amount")]
        public PaymentSummary paid_amount { get; set; }

        /// <summary>
        /// Payment summary of invoice data including the amount refunded through PayPal and other sources.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "refunded_amount")]
        public PaymentSummary refunded_amount { get; set; }
    }
}
