//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using System.Collections.Generic;
using Newtonsoft.Json;

namespace PayPal.Api
{
    public class BankAccountsList : PayPalSerializableObject
    {
        /// <summary>
        /// A list of bank account resources
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "bank_accounts")]
        public List<BankAccount> bank_accounts { get; set; }

        /// <summary>
        /// Number of items returned in each range of results. Note that the last results range could have fewer items than the requested number of items.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "count")]
        public int count { get; set; }

        /// <summary>
        /// Identifier of the next element to get the next range of results.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "next_id")]
        public string next_id { get; set; }
    }
}
