//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using Newtonsoft.Json;

namespace PayPal.Api
{
    public class FundingInstrument : PayPalSerializableObject
    {
        /// <summary>
        /// Credit Card information.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "credit_card")]
        public CreditCard credit_card { get; set; }

        /// <summary>
        /// Credit Card information.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "credit_card_token")]
        public CreditCardToken credit_card_token { get; set; }

        /// <summary>
        /// Payment Card information.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "payment_card")]
        public PaymentCard payment_card { get; set; }

        /// <summary>
        /// Bank Account information.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "bank_account")]
        public ExtendedBankAccount bank_account { get; set; }

        /// <summary>
        /// Bank Account information.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "bank_account_token")]
        public BankToken bank_account_token { get; set; }

        /// <summary>
        /// Credit funding information.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "credit")]
        public Credit credit { get; set; }

        /// <summary>
        /// Incentive funding information.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "incentive")]
        public Incentive incentive { get; set; }

        /// <summary>
        /// Carrier account token information.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "carrier_account_token")]
        public CarrierAccountToken carrier_account_token { get; set; }
    }
}
