//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using Newtonsoft.Json;

namespace PayPal.Api
{
    /// <summary>
    /// A JSON patch object that you can use to apply partial updates to resources.
    /// <para>
    /// See <a href="https://developer.paypal.com/docs/api/">PayPal Developer documentation</a> for more information.
    /// </para>
    /// </summary>
    public class Patch : PayPalSerializableObject
    {
        /// <summary>
        /// The operation to perform.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "op")]
        public string op { get; set; }

        /// <summary>
        /// A JSON pointer that references a location in the target document where the operation is performed. A `string` value.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "path")]
        public string path { get; set; }

        /// <summary>
        /// The value to apply based on the operation. The `remove` operation does not require a `value`.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "value")]
        public object value { get; set; }

        /// <summary>
        /// A JSON pointer that references the location in the target document from which to move the value. A `string` value. Required for the `move` operation.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "from")]
        public string from { get; set; }
    }
}
