//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace PayPal.Api
{
    public class PayoutItem : PayPalSerializableObject
    {
        /// <summary>
        /// The type of identification for the payment receiver. If this field is provided, the payout items without a `recipient_type` will use the provided value. If this field is not provided, each payout item must include a value for the `recipient_type`. 
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "recipient_type")]
        [JsonConverter(typeof(StringEnumConverter))]
        public PayoutRecipientType recipient_type { get; set; }

        /// <summary>
        /// The amount of money to pay a receiver.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "amount")]
        public Currency amount { get; set; }

        /// <summary>
        /// Note for notifications. The note is provided by the payment sender. This note can be any string. 4000 characters max.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "note")]
        public string note { get; set; }

        /// <summary>
        /// The receiver of the payment. In a call response, the format of this value corresponds to the `recipient_type` specified in the request. 127 characters max.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "receiver")]
        public string receiver { get; set; }

        /// <summary>
        /// A sender-specific ID number, used in an accounting system for tracking purposes. 30 characters max.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "sender_item_id")]
        public string sender_item_id { get; set; }
    }
}
