//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using Newtonsoft.Json;

namespace PayPal.Api
{
    public enum PayoutTransactionStatus
    {
        SUCCESS,
        DENIED,
        PENDING,
        PROCESSING,
        FAILED,
        UNCLAIMED,
        REVERSED,
        ONHOLD,
        BLOCKED,
        CANCELLED
    }
}
