//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using System.Collections.Generic;
using Newtonsoft.Json;

namespace PayPal.Api
{
    public class PayoutBatch : PayPalResourceObject
    {
        /// <summary>
        /// A batch header that includes the generated batch status.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "batch_header")]
        public PayoutBatchHeader batch_header { get; set; }

        /// <summary>
        /// Array of the items in a batch payout.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "items")]
        public List<PayoutItemDetails> items { get; set; }
    }
}
