//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using Newtonsoft.Json;

namespace PayPal.Api
{
    public class RedirectUrls : PayPalSerializableObject
    {
        /// <summary>
        /// Url where the payer would be redirected to after approving the payment.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "return_url")]
        public string return_url { get; set; }

        /// <summary>
        /// Url where the payer would be redirected to after canceling the payment.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "cancel_url")]
        public string cancel_url { get; set; }
    }
}
