//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using System.Collections.Generic;
using Newtonsoft.Json;
using PayPal.Util;

namespace PayPal.Api
{
    /// <summary>
    /// List of merchant templates.
    /// <para>
    /// See <a href="https://developer.paypal.com/docs/api/">PayPal Developer documentation</a> for more information.
    /// </para>
    /// </summary>
    public class Templates : PayPalResource
    {
        /// <summary>
        /// List of addresses in merchant profile.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "addresses")]
        public List<Address> addresses { get; set; }

        /// <summary>
        /// List of emails in merchant profile.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "emails")]
        public List<string> emails { get; set; }

        /// <summary>
        /// List of phone numbers in merchant profile.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "phones")]
        public List<Phone> phones { get; set; }

        /// <summary>
        /// An array of templates.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "templates")]
        public List<Template> templates { get; set; }

        /// <summary>
        /// Shows details for a template, by ID.
        /// </summary>
        /// <param name="apiContext">APIContext used for the API call.</param>
        /// <param name="templateId">The ID of the template for which to show details.</param>
        /// <returns>Template</returns>
        public static Template Get(APIContext apiContext, string templateId)
        {
            // Validate the arguments to be used in the request
            ArgumentValidator.ValidateAndSetupAPIContext(apiContext);
            ArgumentValidator.Validate(templateId, "templateId");

            // Configure and send the request
            var pattern = "v1/invoicing/templates/{0}";
            var resourcePath = SDKUtil.FormatURIPath(pattern, new object[] { templateId });
            return PayPalResource.ConfigureAndExecute<Template>(apiContext, HttpMethod.GET, resourcePath);
        }

        /// <summary>
        /// Lists all merchant-created templates. The list shows the emails, addresses, and phone numbers from the merchant profile.
        /// </summary>
        /// <param name="apiContext">APIContext used for the API call.</param>
        /// <param name="fields">The fields to return in the response. Value is `all` or `none`. Specify `none` to return only the template name, ID, and default attributes.</param>
        /// <returns>Templates</returns>
        public static Templates GetAll(APIContext apiContext, string fields = "all")
        {
            // Validate the arguments to be used in the request
            ArgumentValidator.ValidateAndSetupAPIContext(apiContext);

            var queryParameters = new QueryParameters();
            queryParameters["fields"] = fields;

            // Configure and send the request
            var resourcePath = "v1/invoicing/templates" + queryParameters.ToUrlFormattedString();
            return PayPalResource.ConfigureAndExecute<Templates>(apiContext, HttpMethod.GET, resourcePath);
        }

        /// <summary>
        /// Deletes a template, by ID.
        /// </summary>
        /// <param name="apiContext">APIContext used for the API call.</param>
        public void Delete(APIContext apiContext)
        {
            Templates.Delete(apiContext, this.id);
        }

        /// <summary>
        /// Deletes a template, by ID.
        /// </summary>
        /// <param name="apiContext">APIContext used for the API call.</param>
        /// <param name="templateId">The ID of the template to delete.</param>
        public static void Delete(APIContext apiContext, string templateId)
        {
            // Validate the arguments to be used in the request
            ArgumentValidator.ValidateAndSetupAPIContext(apiContext);
            ArgumentValidator.Validate(templateId, "templateId");

            // Configure and send the request
            apiContext.MaskRequestId = true;
            var pattern = "v1/invoicing/templates/{0}";
            var resourcePath = SDKUtil.FormatURIPath(pattern, new object[] { templateId });
            PayPalResource.ConfigureAndExecute(apiContext, HttpMethod.DELETE, resourcePath);
        }

        /// <summary>
        /// Creates a template.
        /// </summary>
        /// <param name="apiContext">APIContext used for the API call.</param>
        /// <param name="template">Template</param>
        /// <returns>Template</returns>
        public Template Create(APIContext apiContext, Template template)
        {
            // Validate the arguments to be used in the request
            ArgumentValidator.ValidateAndSetupAPIContext(apiContext);
            ArgumentValidator.Validate(template, "template");

            // Configure and send the request
            var resourcePath = "v1/invoicing/templates";
            return PayPalResource.ConfigureAndExecute<Template>(apiContext, HttpMethod.POST, resourcePath, template.ConvertToJson());
        }

        /// <summary>
        /// Updates a template, by ID. In the JSON request body, pass a complete `template` object. The update method does not support partial updates.
        /// </summary>
        /// <param name="apiContext">APIContext used for the API call.</param>
        /// <param name="template">Template</param>
        /// <returns>Template</returns>
        public Template Update(APIContext apiContext, Template template)
        {
            // Validate the arguments to be used in the request
            ArgumentValidator.ValidateAndSetupAPIContext(apiContext);
            ArgumentValidator.Validate(this.id, "Id");
            ArgumentValidator.Validate(template, "template");

            // Configure and send the request
            var pattern = "v1/invoicing/templates/{0}";
            var resourcePath = SDKUtil.FormatURIPath(pattern, new object[] { this.id });
            return PayPalResource.ConfigureAndExecute<Template>(apiContext, HttpMethod.PUT, resourcePath, template.ConvertToJson());
        }
    }
}
