//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using System.Collections.Generic;
using Newtonsoft.Json;

namespace PayPal.Api
{
    /// <summary>
    /// Invoicing template.
    /// <para>
    /// See <a href="https://developer.paypal.com/docs/api/">PayPal Developer documentation</a> for more information.
    /// </para>
    /// </summary>
    public class Template : PayPalResource
    {
        /// <summary>
        /// The ID of the template.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "template_id")]
        public string template_id { get; set; }

        /// <summary>
        /// The template name.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "name")]
        public string name { get; set; }

        /// <summary>
        /// Indicates whether this template is the default merchant template. A merchant can have one default template.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "default")]
        public bool? default { get; set; }

        /// <summary>
        /// Customized invoice data, which is saved as the template.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "template_data")]
        public TemplateData template_data { get; set; }

        /// <summary>
        /// Settings for each template.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "settings")]
        public List<TemplateSettings> settings { get; set; }

        /// <summary>
        /// The unit of measure for the template. Value is quantity, hours, or amount.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "unit_of_measure")]
        public string unit_of_measure { get; set; }

        /// <summary>
        /// Indicates whether this template is a merchant-created custom template. Non-custom templates are system generated.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "custom")]
        public bool? custom { get; set; }
    }
}
