//==============================================================================
//
//  This file was auto-generated by a tool using the PayPal REST API schema.
//  More information: https://developer.paypal.com/docs/api/
//
//==============================================================================
using System.Collections.Generic;
using Newtonsoft.Json;

namespace PayPal.Api
{
    public class WebhookEventTypeList : PayPalSerializableObject
    {
        /// <summary>
        /// A list of Webhooks event-types
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "event_types")]
        public List<WebhookEventType> event_types { get; set; }
    }
}
